import Navbar from '@/components/navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer'
import { Providers } from '@/redux/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'The Movie Database',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}
        suppressHydrationWarning={true}
      >
        <Providers>
          <Navbar />
          <div className='min-h-screen mt-[64px]'>
            {children}
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
